services: 
  user-service: 
    build:
      context: ./user-service
    ports: 
     - 5000:5000
    volumes:
      - ./user-service:/app
  mongo-db:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-db-data:/data/db

volumes:
  mongo-db-data: